### ISSUE TITLE
mTranskey 관련 특허 문제 제기.

### ISSUE THREAD

**Issue by Interval-0** [kimcore/hcs.js#1]
mTranskey는 
보안 키패드 원천기술 특허(제 0880862호,
제 0507712호)
라온시큐어의 특허품입니다.

raon.js 의 일부 코드가 mTransKey의 코드일 것으로 추측되는데,
문제가 우려되어 Issue 올려봅니다.

**Comment by kimcore** [comment]
이슈 감사합니다. 특허된 제품인 TransKey의 코드를 무단 사용한 것은 인지하고 있으며, 추후 TransKey의 코드를 사용하지 않고 재작성할 예정입니다.
