### ISSUE TITLE
registerSurvey 질문 개수

### ISSUE THREAD

**Issue by MelodicRealm** [kimcore/hcs.js#10]
해당 라이브러리에서는 survey에 질문이 4개밖에 없는데, 학교에 따라서 15개까지 설정할 수 있는 것으로 보입니다.
제 학교도 질문이 5개여서 이 라이브러리를 사용하면 등교중지라고 뜹니다.
나머지 질문도 지원해주실 생각 있으신가요?

**Comment by kimcore** [comment]
모든 학교가 5개 질문으로 변경된 듯 합니다. 2.0.6 버전으로 업데이트 하시면 해결됩니다!
