### ISSUE TITLE
cron job 실행시 에러

### ISSUE THREAD

**Issue by suakii** [kimcore/hcs.js#21]
ts-node로 example.ts를 실행하면 정상적으로 실행이 됩니다.
이를 리눅스의 cronjob에 넣고 실행을 하면 다음과 같은 에러가 발생합니다.
혹시 이유를 알 수 있을까요?
크론에서 호출하는 스크립트는 shell 로 되어 있으며 아래 처럼 콘솔에서 동작하는 명령어를 넣어놓았고
이 셀 자체는 실행이 잘 됩니다.
#!/bin/bash
/usr/local/bin/ts-node /root/autoTest/autoCheck.ts > /root/cron.log 2>/root/cron_error.log
그러나 크론에서 위 셀을 부른 에러 메시지는 다음과 같이 나와서 크론에서 실행이 되지 않고 있어서 질문드려봅니다.

/usr/local/lib/node_modules/ts-node/dist/bin.js:24
function main(argv = process.argv.slice(2), entrypointArgs = {}) {
                   ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by kimcore** [comment]
cron에 추가하실 때 `/usr/bin/bash -x script.sh` 형식으로 추가해보시겠어요?

**Comment by suakii** [comment]
> 
네 기존 cron이 다음과 같습니다. 시간은 테스팅 삼아서 수정한 거구요. 말씀해주신 bash의 경로가 저는 /bin/bash 라서 변경하였습니다.
그러나 위와 같이 동일한 에러 메시지가 발생하네요.
* * * * 1-5 /root/autoCheck.sh 2>/root/cron_error.log
* 
제가 제대로 사용을 못하는 건지 저는
폴더 만들고 npm install hcs.js 로 설치하고 
github의 코드 다운 받아서 example 수정 후 ts-node 를 실행해서 정상 동작하는 것을 확인한 상태입니다.
감사합니다.

**Comment by kimcore** [comment]
흠.. 이번엔 `/bin/bash -l -x /root/autoCheck.sh` 명령어로 cron에 추가해보시겠어요? 아마도 cron에서 ts-node를 실행할 때 구버전 nodejs가 사용되는걸로 추정됩니다.

**Comment by suakii** [comment]
> 흠.. 이번엔 `/bin/bash -l -x /root/autoCheck.sh` 명령어로 cron에 추가해보시겠어요? 아마도 cron에서 ts-node를 실행할 때 구버전 nodejs가 사용되는걸로 추정됩니다.

네 바꾸어도 동일한 증상이에요. 버젼을 다 바꾸어 보겠습니다. 감사합니다.

**Comment by kimcore** [comment]
node-cron을 사용해서 코드 작성 후 screen을 통해 지속 실행 시키는 것도 추천드려요. 실제로 저도 그렇게 사용중입니다.
