### ISSUE TITLE
TypeError: response is not iterable

### ISSUE THREAD

**Issue by MelodicRealm** [kimcore/hcs.js#24]
학생을 1명만 등록할 수 있게 바뀐 뒤로? (확인 필요)
`/getUserInfo`의 응답이 `UserInfo`의 배열이 아니라 `UserInfo`만 반환하도록 바뀐 것 같습니다.

때문에 `userInfo()`가 작동하지 않습니다.

**Comment by kimcore** [comment]
`userInfo()`는 `/selectUserGroup`에서 참여자를 모두 불러온 후 각각의 참여자에 대해 `/getUserInfo`에서 `UserInfo`를 받아와 배열로 반환하는 방식입니다. 저는 오류가 나지 않는데, 혹시 정확한 오류 문구를 볼 수 있을까요?

**Comment by MelodicRealm** [comment]
```js
TypeError: response is not iterable
    at Object.<anonymous> (/home/username/folder/node_modules/hcs.js/dist/userInfo.js:27:28)
    at Generator.next (<anonymous>)
    at fulfilled (/home/username/folder/node_modules/hcs.js/dist/userInfo.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ```

**Comment by kimcore** [comment]
레포 클론하셔서 `response`가 무슨 내용인지 확인해보셔야 할 것 같네요.

**Comment by MelodicRealm** [comment]
`respone`:

```js
{
  message: '죄송합니다 일시적인 장애가있습니다. 로그아웃 후 재로그인 또는  페이지 새로고침후 재시도하세요[1003]'
}
```

**Comment by kimcore** [comment]
`secondLogin`이나 `registerSurvey`같은 함수들은 정상적으로 작동한다는 말씀이신거죠?

**Comment by MelodicRealm** [comment]
`userInfo` 제외하고 전부 정상작동합니다.

**Comment by MelodicRealm** [comment]
혹시 제 계정의 문제가 아닐까 해서 지인 계정으로도 해봤는데 같은 오류가 발생합니다.

**Comment by kimcore** [comment]
저도 계정 여러개로 시도해봤으나 오류가 재현되지 않아서.. 혹시 kimcoreovo@gmail.com 으로 학교명/이름/생년월일을 제공해주실 수 있을까요? 확인 후에 메일은 완전 삭제하겠습니다.

**Comment by MelodicRealm** [comment]
보냈습니다!

**Comment by kimcore** [comment]
앗.. 다시 확인해보니 `userInfo()` 에는 2차 로그인 토큰을 사용해야 하는데, 문서와 코드에 잘못 적혀있었네요. 혼란을 드려 죄송합니다

**Comment by kimcore** [comment]
보내주신 개인정보는 완전 삭제하였습니다! 문서 수정후에 이슈 닫도록 할게요
